In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('quick_commerce_data_raw.csv')

df.head()
print(df)

        Order_ID           Company      City  Customer_Age  Order_Value  \
0        1000001  Swiggy Instamart     Noida            46    702.33750
1        1000002  Flipkart Minutes  Amritsar            56   1007.30000
2        1000003  Flipkart Minutes    Mumbai            18   1211.66000
3        1000004  Swiggy Instamart     Delhi            23   1179.05925
4        1000005             Dunzo    Mumbai            44    586.02550
...          ...               ...       ...           ...          ...
999995   1999996        Big Basket    Mumbai            48     72.33000
999996   1999997  Swiggy Instamart    Mumbai            33   1509.66300
999997   1999998          Jio Mart     Noida            29    637.32300
999998   1999999             Dunzo      Pune            42   1103.12100
999999   2000000        Amazon Now   Chennai            19    758.58860

        Delivery_Time_Min  Distance_Km  Items_Count     Product_Category  \
0                  19.182        11.97         12.0                Dairy
1                  19.644        12.74         10.0               Snacks
2                  16.910         4.85          NaN        Personal Care
3                   5.864         6.44          2.0                Dairy
4                  12.470         2.45         13.0            Household
...                   ...          ...          ...                  ...
999995             17.806         3.01         19.0  Fruits & Vegetables
999996             18.306        10.51          9.0            Beverages
999997             17.590         2.65          6.0            Groceries
999998             12.656         7.76         12.0               Snacks
999999             17.670         9.45         13.0               Snacks

          Payment_Method  Customer_Rating  Discount_Applied  \
0                 Wallet              2.1                 1
1       Cash on Delivery              2.3                 0
2       Cash on Delivery              3.3                 0
3            Credit Card              5.0                 1
4                 Wallet              3.7                 0
...                  ...              ...               ...
999995            Wallet              4.2                 0
999996        Debit Card              4.1                 1
999997  Cash on Delivery              3.4                 0
999998            Wallet              4.0                 1
999999       Credit Card              4.1                 0

        Delivery_Partner_Rating
0                           3.2
1                           3.2
2                           3.8
3                           5.0
4                           4.8
...                         ...
999995                      2.8
999996                      3.5
999997                      4.6
999998                      4.5
999999                      4.8

[1000000 rows x 13 columns]

In [2]:
#data structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   Order_ID                 1000000 non-null  int64
 1   Company                  1000000 non-null  str
 2   City                     948000 non-null   str
 3   Customer_Age             1000000 non-null  int64
 4   Order_Value              1000000 non-null  float64
 5   Delivery_Time_Min        1000000 non-null  float64
 6   Distance_Km              1000000 non-null  float64
 7   Items_Count              965000 non-null   float64
 8   Product_Category         1000000 non-null  str
 9   Payment_Method           1000000 non-null  str
 10  Customer_Rating          953000 non-null   float64
 11  Discount_Applied         1000000 non-null  int64
 12  Delivery_Partner_Rating  895863 non-null   float64
dtypes: float64(6), int64(3), str(4)
memory usage: 99.2 MB

In [3]:
#data summary statistics
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,965000.000000,953000.000000,1000000.000000,895863.000000
mean,1.500000e+06,38.470387,571.643584,16.452412,7.750231,9.998317,3.042072,0.400883,3.749257
std,2.886753e+05,12.118520,382.784520,6.257172,4.186665,5.478725,1.186872,0.490078,0.722121
min,1.000001e+06,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.000000,2.500000
25%,1.250001e+06,28.000000,287.840150,12.368000,4.130000,5.000000,2.000000,0.000000,3.100000
50%,1.500000e+06,38.000000,531.324600,16.342000,7.740000,10.000000,3.000000,0.000000,3.700000
75%,1.750000e+06,49.000000,796.182500,20.196000,11.380000,15.000000,4.000000,1.000000,4.400000
max,2.000000e+06,59.000000,13877.325000,40.000000,15.000000,19.000000,5.000000,1.000000,5.000000

In [4]:
# checking for missing values isnull().sum() or isna().sum() 
# can be used to check for missing values in the dataset. 
# The output will show the number of missing values in each column of the dataframe.
df.isnull().sum()

Order_ID                        0
Company                         0
City                        52000
Customer_Age                    0
Order_Value                     0
Delivery_Time_Min               0
Distance_Km                     0
Items_Count                 35000
Product_Category                0
Payment_Method                  0
Customer_Rating             47000
Discount_Applied                0
Delivery_Partner_Rating    104137
dtype: int64

In [5]:
# shows the rows with missing values in the dataframe. 
# The output will be a new dataframe that contains only the rows with missing values.
df[df.isnull().any(axis=1)]

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0,3.8
6,1000007,Blinkit,Bengluru,37,516.86480,18.476,12.46,19.0,Snacks,Debit Card,2.8,0,NaN
17,1000018,Zepto,Delhi,23,1041.42975,5.000,14.74,18.0,Snacks,Wallet,NaN,1,NaN
21,1000022,Blinkit,NaN,41,716.89860,17.804,11.34,7.0,Beverages,Credit Card,2.7,1,3.6
22,1000023,Jio Mart,Delhi,48,50.00000,8.498,0.83,3.0,Snacks,Cash on Delivery,3.1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999966,1999967,Dunzo,NaN,39,783.89250,18.820,14.70,NaN,Household,Wallet,3.1,1,4.9
999975,1999976,Amazon Now,Bengluru,34,515.89380,21.294,10.49,10.0,Fruits & Vegetables,Wallet,NaN,1,3.0
999981,1999982,Amazon Now,NaN,33,939.34470,21.080,11.80,18.0,Dairy,Wallet,3.2,1,4.4
999983,1999984,Swiggy Instamart,Hyderabad,42,50.00000,13.386,2.31,2.0,Groceries,Wallet,NaN,0,3.2
999990,1999991,Amazon Now,Delhi,39,781.65420,7.158,6.93,NaN,Personal Care,Wallet,4.0,0,3.9

In [6]:
#shows the rows with all missing values in the dataframe.
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [Order_ID, Company, City, Customer_Age, Order_Value, Delivery_Time_Min, Distance_Km, Items_Count, Product_Category, Payment_Method, Customer_Rating, Discount_Applied, Delivery_Partner_Rating]
Index: []

In [7]:
df2 = df.dropna(subset=['City']).copy()
print("Number of rows after dropping rows with missing values in 'City' column:", len(df2))
df2.head()

Number of rows after dropping rows with missing values in 'City' column: 948000

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Noida,46,702.33750,19.182,11.97,12.0,Dairy,Wallet,2.1,1,3.2
1,1000002,Flipkart Minutes,Amritsar,56,1007.30000,19.644,12.74,10.0,Snacks,Cash on Delivery,2.3,0,3.2
2,1000003,Flipkart Minutes,Mumbai,18,1211.66000,16.910,4.85,NaN,Personal Care,Cash on Delivery,3.3,0,3.8
3,1000004,Swiggy Instamart,Delhi,23,1179.05925,5.864,6.44,2.0,Dairy,Credit Card,5.0,1,5.0
4,1000005,Dunzo,Mumbai,44,586.02550,12.470,2.45,13.0,Household,Wallet,3.7,0,4.8

In [8]:
x = df2['Items_Count'].mode()[0] # Find the mode (scalar) of 'Items_Count'
df['Items_Count'] = df['Items_Count'].fillna(x) # Fill missing values with the mode

print("Number of rows after filling missing values in 'Items_Count' column:", len(df2))
print("Items_Count mode:", x)

Number of rows after filling missing values in 'Items_Count' column: 948000
Items_Count mode: 19.0

In [9]:
df['Items_Count'].fillna(x, inplace=True) # Fill missing values with the mode but using inplace=True to modify the original dataframe directly

C:\Users\JUNE VERON\AppData\Local\Temp\ipykernel_7108\3761109664.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Items_Count'].fillna(x, inplace=True) # Fill missing values with the mode but using inplace=True to modify the original dataframe directly

0         12.0
1         10.0
2         19.0
3          2.0
4         13.0
          ...
999995    19.0
999996     9.0
999997     6.0
999998    12.0
999999    13.0
Name: Items_Count, Length: 1000000, dtype: float64

In [10]:
df2.isna().sum()

Order_ID                       0
Company                        0
City                           0
Customer_Age                   0
Order_Value                    0
Delivery_Time_Min              0
Distance_Km                    0
Items_Count                33228
Product_Category               0
Payment_Method                 0
Customer_Rating            44575
Discount_Applied               0
Delivery_Partner_Rating    98694
dtype: int64

In [11]:
x = df2['Items_Count'].mode()[0] # Find the mode (scalar) of 'Items_Count'
df2['Items_Count'] = df2['Items_Count'].fillna(x) # Fill missing values with the mode
df2['Items_Count']

0         12.0
1         10.0
2         19.0
3          2.0
4         13.0
          ...
999995    19.0
999996     9.0
999997     6.0
999998    12.0
999999    13.0
Name: Items_Count, Length: 948000, dtype: float64

In [12]:
df2['Items_Count'].isna()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Name: Items_Count, Length: 948000, dtype: bool

In [14]:
print(df2)

        Order_ID           Company      City  Customer_Age  Order_Value  \
0        1000001  Swiggy Instamart     Noida            46    702.33750
1        1000002  Flipkart Minutes  Amritsar            56   1007.30000
2        1000003  Flipkart Minutes    Mumbai            18   1211.66000
3        1000004  Swiggy Instamart     Delhi            23   1179.05925
4        1000005             Dunzo    Mumbai            44    586.02550
...          ...               ...       ...           ...          ...
999995   1999996        Big Basket    Mumbai            48     72.33000
999996   1999997  Swiggy Instamart    Mumbai            33   1509.66300
999997   1999998          Jio Mart     Noida            29    637.32300
999998   1999999             Dunzo      Pune            42   1103.12100
999999   2000000        Amazon Now   Chennai            19    758.58860

        Delivery_Time_Min  Distance_Km  Items_Count     Product_Category  \
0                  19.182        11.97         12.0                Dairy
1                  19.644        12.74         10.0               Snacks
2                  16.910         4.85         19.0        Personal Care
3                   5.864         6.44          2.0                Dairy
4                  12.470         2.45         13.0            Household
...                   ...          ...          ...                  ...
999995             17.806         3.01         19.0  Fruits & Vegetables
999996             18.306        10.51          9.0            Beverages
999997             17.590         2.65          6.0            Groceries
999998             12.656         7.76         12.0               Snacks
999999             17.670         9.45         13.0               Snacks

          Payment_Method  Customer_Rating  Discount_Applied  \
0                 Wallet              2.1                 1
1       Cash on Delivery              2.3                 0
2       Cash on Delivery              3.3                 0
3            Credit Card              5.0                 1
4                 Wallet              3.7                 0
...                  ...              ...               ...
999995            Wallet              4.2                 0
999996        Debit Card              4.1                 1
999997  Cash on Delivery              3.4                 0
999998            Wallet              4.0                 1
999999       Credit Card              4.1                 0

        Delivery_Partner_Rating
0                           3.2
1                           3.2
2                           3.8
3                           5.0
4                           4.8
...                         ...
999995                      2.8
999996                      3.5
999997                      4.6
999998                      4.5
999999                      4.8

[948000 rows x 13 columns]

In [15]:
df2.isna().sum()

Order_ID                       0
Company                        0
City                           0
Customer_Age                   0
Order_Value                    0
Delivery_Time_Min              0
Distance_Km                    0
Items_Count                    0
Product_Category               0
Payment_Method                 0
Customer_Rating            44575
Discount_Applied               0
Delivery_Partner_Rating    98694
dtype: int64

In [16]:
df.isna().sum()

Order_ID                        0
Company                         0
City                        52000
Customer_Age                    0
Order_Value                     0
Delivery_Time_Min               0
Distance_Km                     0
Items_Count                     0
Product_Category                0
Payment_Method                  0
Customer_Rating             47000
Discount_Applied                0
Delivery_Partner_Rating    104137
dtype: int64

In [17]:
df.fillna?

Signature:
df.fillna(
    value: 'Hashable | Mapping | Series | DataFrame',
    *,
    axis: 'Axis | None' = None,
    inplace: 'bool' = False,
    limit: 'int | None' = None,
) -> 'Self'
Docstring:
Fill NA/NaN values with `value`.

Parameters
----------
value : scalar, dict, Series, or DataFrame
    Value to use to fill holes (e.g. 0), alternately a
    dict/Series/DataFrame of values specifying which value to use for
    each index (for a Series) or column (for a DataFrame).  Values not
    in the dict/Series/DataFrame will not be filled. This value cannot
    be a list.
axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
    Axis along which to fill missing values. For `Series`
    this parameter is unused and defaults to 0.
inplace : bool, default False
    If True, fill in-place. Note: this will modify any
    other views on this object (e.g., a no-copy slice for a column in a
    DataFrame).
limit : int, default None
    This is the maximum number of entries along the entire axis
    where NaNs will be filled. Must be greater than 0 if not None.

Returns
-------
Series/DataFrame
    Object with missing values filled.

See Also
--------
ffill : Fill values by propagating the last valid observation to next valid.
bfill : Fill values by using the next valid observation to fill the gap.
interpolate : Fill NaN values using interpolation.
reindex : Conform object to new index.
asfreq : Convert TimeSeries to specified frequency.

Notes
-----
For non-object dtype, ``value=None`` will use the NA value of the dtype.
See more details in the :ref:`Filling missing data<missing_data.fillna>`
section.

Examples
--------
>>> df = pd.DataFrame(
...     [
...         [np.nan, 2, np.nan, 0],
...         [3, 4, np.nan, 1],
...         [np.nan, np.nan, np.nan, np.nan],
...         [np.nan, 3, np.nan, 4],
...     ],
...     columns=list("ABCD"),
... )
>>> df
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

Replace all NaN elements with 0s.

>>> df.fillna(0)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
2, and 3 respectively.

>>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
>>> df.fillna(value=values)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  2.0  1.0
2  0.0  1.0  2.0  3.0
3  0.0  3.0  2.0  4.0

Only replace the first NaN element.

>>> df.fillna(value=values, limit=1)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  NaN  1.0
2  NaN  1.0  NaN  3.0
3  NaN  3.0  NaN  4.0

When filling using a DataFrame, replacement happens along
the same column names and same indices

>>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
>>> df.fillna(df2)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  NaN
3  0.0  3.0  0.0  4.0

Note that column D is not affected since it is not present in df2.
File:      ~\onedrive\desktop\quick commerce data anaysis\.venv\lib\site-packages\pandas\core\generic.py
Type:      method